### PR TITLE
JCLOUDS-1117 & JCLOUDS-1118 - docker container configuration fixes

### PR DESCRIPTION
**Pull request by kwart**
JIRAs:
* https://issues.apache.org/jira/browse/JCLOUDS-1117
* https://issues.apache.org/jira/browse/JCLOUDS-1118

This pull request contains Docker configuration fixes.

### CODE REVIEW

**Comment by nacx** [comment]
Thanks @kwart! Looks good to me. @andreaturli @grkvlt want to have a look?

**Comment by kwart** [comment]
As I look into it, I've probably forgot to add some fields to `HostConfig`. I'll fix it and try to add some more test coverage.

So don't merge this yet, please.

**Comment by kwart** [comment]
I've re-checked the fields and there was nothing forgotten.

Nevertheless I've added test coverage for Container parsing for Docker Remote API version 1.21 and I discovered missing `Nullable` annotation by 2 fields.

The new tests and fixes are in a new commit. I can squash it to the previous (2nd) one.

**Comment by nacx** [comment]
Squashed the last commit into the second one and pushed to master as [c269e016](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/c269e016) and [6d078e69](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/6d078e69). Thanks @kwart!

**Pull request closed without merging**
