### PR TITLE
Remove duplicated sharedstorage test inputs

### PR DESCRIPTION
**Pull request by andrewgaul**

### CODE REVIEW

**Comment by demobox** [comment]
Thanks for catching this, @andrewgaul! Do we know which of the sets of resources is newer? Or are they identical?

Also, on a separate note, would it be worth sending an email about this to the dev list and/or adding this to the wiki or documentation?

/cc @nacx

**Comment by andrewgaul** [comment]
`diff -r oneandone/src/test/resources/shared*` confirms that these files are identical.

**Comment by demobox** [comment]
> diff -r oneandone/src/test/resources/shared* confirms that these files are identical

Thanks, @andrewgaul!

**Comment by nacx** [comment]
Pushed to master as [cb06b681](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/cb06b681).

**Pull request closed without merging**
