### PR TITLE
JCLOUDS-104: Clean up jclouds-labs POMs

### PR DESCRIPTION
**Pull request by andreaturli**
- Change each individual project in the repo, and the root pom.xml to use jclouds-project as a parent.
- Replace all occurrences of jclouds.version by project.parent.version.
  similarly to jclouds-labs-openstack repo

@nacx can you have a look?

### CODE REVIEW

**Comment by nacx** [comment]
Many thanks @andreaturli! Just a couple things:

* Add the jira issue ID in the commit message
* Remove the `jclouds.version` property from the root pom.xml to make sure it is not used again by mistake.

**Comment by nacx** [comment]
lgtm. Thanks!

**Comment by andrewgaul** [comment]
@andreaturli Do you plan to continue with this PR?  This seems like the right thing to do.

**Comment by andreaturli** [comment]
I'll rebase this old PR asap

**Comment by andreaturli** [comment]
I think I've rebased it, address @nacx comments; let's see if the builder is happy

**Comment by andrewgaul** [comment]
Can you add the new providers like b2 to this PR?

**Comment by andrewgaul** [comment]
Can you update `jdbc/pom.xml` and `h2-jdbc/pom.xml` as well?  I found these via:

```
find -name pom.xml | xargs grep -A 4 '<parent>' | grep artifactId | grep labs
```

**Comment by andrewgaul** [comment]
@nacx Any comments?  Otherwise looks good to me.

**Comment by andreaturli** [comment]
done, thx @andrewgaul for the review

**Comment by andreaturli** [comment]
rebuild please

**Comment by nacx** [comment]
+1! Thanks guys!

**Comment by demobox** [comment]
Have we run a dummy release with the changed code? The original `jclouds.version` stuff was added to decouple the local POM version (which was a snapshot) from the parent version (which, at the moment when a release is run, is no longer a snapshot).

I'd say it's worth testing whether the release script still works with the changed code.

**Comment by nacx** [comment]
Yes, +1 to test that before merging, but I'd say it will work. The release process builds the repos in order, and everything should be in the local Maven repo (note that we don't use the `relativePath` in the parent configuration here).

**Comment by andrewgaul** [comment]
@andreaturli Any updates on this pull request?

**Comment by andreaturli** [comment]
sorry @andrewgaul don't really recall the details of it and JCLOUDS-104 has a long history.

Let's restart the discussion if you think it is still useful

**Comment by andreaturli** [comment]
rebuild please

**Comment by szuperbody2405** [comment]
https://plashporn.com

**Comment by andrewgaul** [comment]
Closed due to inactivity.

**Pull request closed without merging**
