### PR TITLE
fix domain object

### PR DESCRIPTION
**Pull request by andreaturli**

### CODE REVIEW

**Comment by nacx** [comment]
rebuild please

**Comment by gaul** [comment]
@nacx I encountered similar CloudBees weirdness in jclouds/jclouds#1148 but could not find a solution.

**Comment by nacx** [comment]
@demobox have you seen this issue before? Looks like a bug in CloudBees we could report?

**Comment by nacx** [comment]
Builds should now be fixed, rebuild please

**Comment by nacx** [comment]
@andreaturli Apart from the Tier test failures it looks like there are actual test failures related to this change. Mind having a look?
@gaul It looks like there are test failure sin jclouds-labs regarding the Tiers change. Mind having a look?

**Comment by andreaturli** [comment]
rebind please

**Comment by andreaturli** [comment]
rebuild please

**Comment by andreaturli** [comment]
Merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/02c02a36)

**Pull request closed without merging**
