### PR TITLE
[JCLOUDS-664] Fixing live test execution on Azure

### PR DESCRIPTION
**Pull request by ilgrosso**
Functionally equivalent to #147 but with only two commits as required by JClouds policies.

### CODE REVIEW

**Comment by andreaturli** [comment]
Thanks @ilgrosso

I've tried your PR using my azure account. Please find the result of my run [here](https://gist.github.com/andreaturli/0a206fa810d749563bc8)

FYI I've started from a clean situation: no network, no cloudservice, no storage account.

**Comment by ilgrosso** [comment]
Hi @andreaturli, could you please provide the whole live execution log (including command-line) and not just the tail? Thanks.

**Comment by andreaturli** [comment]
Sure!

'mvn clean install -Plive -Dtest.azurecompute.endpoint=https://management.core.windows.net/341751b0-f348-45ce-xxxx-41cc68b4b45f -Dtest.azurecompute.credential=password -Dtest.azurecompute.identity=/Users/andrea/.jclouds/azure.p12'

I'm getting this [output](https://gist.githubusercontent.com/andreaturli/111200dd9068e97580ea/raw/gistfile1.sh)

**Comment by fmartelli** [comment]
Hi Andrea, it seems that you have excuted the test without applying the pull request before: actually, that was exactly the output before our changes.

Your output is not compliant with the work done till now. For example, I see that you have several 409 errors returned, a lot of work has been done to manage this conflict errors. You shouldn't have that kind of error. Further, your failure lines don't match with my local code.

Is the patch request not including all changes or have you missed something applying it?
Please, can you check it again?

Best regards,
F.

**Comment by fmartelli** [comment]
Sorry, I've forgotten to say that recently MS changed something into its platform. The following error comes from these.

java.lang.IllegalArgumentException: No enum constant org.jclouds.azurecompute.domain.RoleSize.Type.A10

A10 role type has to be added and the role type reading mechanism has to be improved.

Best regards,
F.

**Comment by andreaturli** [comment]
thanks @fmartelli and @ilgrosso 

I thinks there was a problem with my test. [Here](https://gist.githubusercontent.com/andreaturli/e17ee3f9b305096e4138/raw/live-tests) the results using #148

**Comment by ilgrosso** [comment]
@andreaturli @nacx This commit introduces `A10` / `A11` in `org.jclouds.azurecompute.domain.RoleSize.Type` and properly defaults to `UNRECOGNIZED` for all enum types which provides that - by adding a static `fromString` method.

**Comment by andreaturli** [comment]
much better now,

`Failed tests:
  OSImageApiLiveTest.testList:58->checkOSImage:78 Locations not in [North Europe, West Europe, East US 2, Central US, South Central US, West US, East US, Southeast Asia, East Asia, Japan West, Japan East] :[East Asia, Southeast Asia, Australia East, Australia Southeast, North Europe, West Europe, Japan East, Japan West, Central US, East US, East US 2, South Central US, West US] expected [true] but found [false]
  AzureComputeSecurityGroupExtensionLiveTest>BaseSecurityGroupExtensionLiveTest.testCreateSecurityGroup:96 » IllegalState
  AzureComputeSecurityGroupExtensionLiveTest>BaseSecurityGroupExtensionLiveTest.testDeleteSecurityGroup:376 expected [true] but found [false]

Tests run: 30, Failures: 3, Errors: 0, Skipped: 6`

is it the same for you guys, @ilgrosso and @fmartelli ?

**Comment by ilgrosso** [comment]
@andreaturli, we normally get no errors at all; such failures look quite strange, especially the first one which is very basic.
Could you please check if there is something strange with the checked sources or your subscription data (a clean situation always helps).

**Comment by andreaturli** [comment]
using your last version, all live tests are now green!

Let's wait for @nacx's proper review to merge it 

Thanks!

**Comment by nacx** [comment]
The PR looks good to me. But I'm missing the storage api mock tests.

It can't be merged, though, because it contains the unrelated traffic manager operations commit. Please, develop each feature in its own topic branch instead of working in master, so we can properly have one PR per feature. Can you remove the last commit from the PR, and move it to a different branch? You can open a PR from that branch, to get that commit merged.

**Comment by ilgrosso** [comment]
> The PR looks good to me. But I'm missing the storage api mock tests.

The intent of this PR was to fix the live test execution: we can address this need in a future PR.

> It can't be merged, though, because it contains the unrelated traffic manager operations commit

You are right, @fmartelli should have committed to the master branch by mistake: we will remove the commit from master and place it on a separate branch tomorrow.

Thanks for your review.

**Comment by ilgrosso** [comment]
@nacx I have just removed the "offending" commit from master and created a dedicated branch with it (for future PR)

**Comment by fmartelli** [comment]
Sorry @nacx, my bad. Thanks @ilgrosso for your fix.
Please, consider that traffic manager operations are ready for a new PR.

**Comment by nacx** [comment]
Pushed to master. Thanks!

**Pull request closed without merging**
