### PR TITLE
JCLOUDS-853: Improve Create VirtualMachine Deployment

### PR DESCRIPTION
**Pull request by hsbhathiya**
Jclouds-853: Improve Create Virtual Machine Deployment [1]

Create Virtual Machine Deployment [2] Implementation should support different combination that can be used to create a virtual machine deployment.
[1] https://issues.apache.org/jira/browse/JCLOUDS-853
[2] https://msdn.microsoft.com/en-us/library/azure/jj157194.aspx

### CODE REVIEW

**Comment by fmartelli** [comment]
hi @hsbhathiya, since #163 added reserved IP addresses support, could you handle this information during deployment creation? Thank you in advance.

**Comment by hsbhathiya** [comment]
@fmartelli I'll look into it change the PR as required

**Comment by nacx** [comment]
@hsbhathiya Any plan to have this PR rebased soon?

**Comment by ilgrosso** [comment]
@hsbhathiya Could you rebase this, please?

**Comment by hsbhathiya** [comment]
@ilgrosso  Rebase this in  https://github.com/jclouds/jclouds-labs/pull/171

**Comment by ilgrosso** [comment]
Thanks @hsbhathiya - @nacx can you take a look at #171?

**Pull request closed without merging**
