### PR TITLE
fix azure-arm features live tests

### PR DESCRIPTION
**Pull request by andreaturli**
When running in isolation the *LiveTests are working fine, they fail when running all together from maven. (see https://gist.github.com/andreaturli/2725723193ee1a8362f175e8e8c76ee8)

### CODE REVIEW

**Comment by nacx** [comment]
Build failed due to checkstyle errors:
https://jclouds.ci.cloudbees.com/job/jclouds-labs-pull-requests/1447/org.apache.jclouds.labs$azurecompute-arm/violations/

**Comment by nacx** [comment]
Can you share the live test output after this change?
The base compute service has some issues regarding access to the VM. I will be able to allocate some time to look at it next week, so I wouldn't worry about those.

**Comment by andreaturli** [comment]
@nacx happy to share the live tests results, **but** it would be useful to merge first https://github.com/jclouds/jclouds-labs/pull/308 as it speed up the live tests significantely

**Comment by andreaturli** [comment]
```
Failed tests:
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCompareSizes:887->BaseComputeServiceLiveTest.doCompareSizes:891 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCreateAndRunAService:733->BaseComputeServiceLiveTest.createAndRunAServiceInGroup:747->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testImageById:212 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testOptionToNotBlock:850->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testWeCanCancelTasks:282->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testTemplateMatch:341->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureTemplateBuilderLiveTest>BaseTemplateBuilderLiveTest.testGetAssignableLocations:104->BaseTemplateBuilderLiveTest.assertProvider:225 Sets differ: expected [US-IA, US-VA, US-IL, US-TX, US-CA, IE, NL, HK, SG, JP-11, JP-27, BR, AU-NSW, AU-VIC] but got [US-IA, US-VA, US-IL, US-TX, US-CA, IE, NL, HK, SG, JP-11, JP-27, BR, AU-NSW, AU-VIC, IN-GA, IN-TN, IN-MH, CN-SH, CN-BJ, CA-ON, CA-QC]
  AzureTemplateBuilderLiveTest>BaseTemplateBuilderLiveTest.testTemplateBuilderWithLoginUserSpecified:189->BaseTemplateBuilderLiveTest.tryOverrideUsingPropertyKey:213 expected [[user=foo, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=true]] but found [[user=jclouds, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=false]]
  AzureComputeImageExtensionLiveTest>BaseImageExtensionLiveTest.testCreateImage:106 » Execution
  NetworkInterfaceCardApiLiveTest.createNetworkInterfaceCard:89 » HttpResponse c...
  NetworkSecurityGroupApiLiveTest.deleteNetworkSecurityGroupDoesNotExist:61 » IllegalState
  NetworkSecurityRuleApiLiveTest.deleteNetworkSecurityRuleDoesNotExist:86 » IllegalState
  SubnetApiLiveTest.deleteSubnetResourceDoesNotExist:61 expected [false] but found [true]
  VirtualNetworkApiLiveTest.deleteVirtualNetworkResourceDoesNotExist:56 expected [false] but found [true]
  PublicIPAddressApiLiveTest.getPublicIPAddress:103 » NullPointer
  PublicIPAddressApiLiveTest.listPublicIPAddresses:126 expected [true] but found [false]
  NetworkSecurityGroupApiLiveTest.tearDown:56->BaseAzureComputeApiLiveTest.deleteResourceGroup:144 » NullPointer
  NetworkSecurityRuleApiLiveTest.tearDown:81->BaseAzureComputeApiLiveTest.deleteResourceGroup:144 » NullPointer
  PublicIPAddressApiLiveTest.deletePublicIPAddress:132 » ResourceNotFound org.jc...
  PublicIPAddressApiLiveTest.tearDown:56->BaseAzureComputeApiLiveTest.deleteResourceGroup:144 » NullPointer
  SubnetApiLiveTest.deleteSubnet:92 » ResourceNotFound org.jclouds.http.HttpResp...
  SubnetApiLiveTest.tearDown:55->BaseAzureComputeApiLiveTest.deleteResourceGroup:144 » NullPointer
  VirtualNetworkApiLiveTest.deleteVirtualNetwork:89 » ResourceNotFound org.jclou...
  VirtualNetworkApiLiveTest.tearDown:50->BaseAzureComputeApiLiveTest.deleteResourceGroup:144 » NullPointer
  VirtualMachineApiLiveTest.setup:82->BaseAzureComputeApiLiveTest.getOrCreateNetworkInterfaceCard:245 » HttpResponse

Tests run: 116, Failures: 25, Errors: 0, Skipped: 47
```

**Comment by andreaturli** [comment]
New results
```
Failed tests:
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCompareSizes:887->BaseComputeServiceLiveTest.doCompareSizes:891 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCreateAndRunAService:733->BaseComputeServiceLiveTest.createAndRunAServiceInGroup:747->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testImageById:212 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testOptionToNotBlock:850->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testWeCanCancelTasks:282->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testTemplateMatch:341->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureTemplateBuilderLiveTest>BaseTemplateBuilderLiveTest.testGetAssignableLocations:104->BaseTemplateBuilderLiveTest.assertProvider:225 Sets differ: expected [US-IA, US-VA, US-IL, US-TX, US-CA, IE, NL, HK, SG, JP-11, JP-27, BR, AU-NSW, AU-VIC] but got [US-IA, US-VA, US-IL, US-TX, US-CA, IE, NL, HK, SG, JP-11, JP-27, BR, AU-NSW, AU-VIC, IN-GA, IN-TN, IN-MH, CN-SH, CN-BJ, CA-ON, CA-QC]
  AzureTemplateBuilderLiveTest>BaseTemplateBuilderLiveTest.testTemplateBuilderWithLoginUserSpecified:189->BaseTemplateBuilderLiveTest.tryOverrideUsingPropertyKey:213 expected [[user=foo, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=true]] but found [[user=jclouds, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=false]]
  AzureComputeImageExtensionLiveTest>BaseImageExtensionLiveTest.testCreateImage:100 » RunNodes
  DeploymentApiLiveTest.testValidate:160 expected object to not be null
  VirtualMachineApiLiveTest.testStop:141 » NullPointer
  VirtualMachineApiLiveTest.tearDown:100->deleteStorageService:314 » ResourceNotFound

Tests run: 109, Failures: 12, Errors: 0, Skipped: 20
```
almost there!

**Comment by andreaturli** [comment]
```
Results :

Failed tests:
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCompareSizes:887->BaseComputeServiceLiveTest.doCompareSizes:891 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCreateAndRunAService:733->BaseComputeServiceLiveTest.createAndRunAServiceInGroup:747->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testImageById:212 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testOptionToNotBlock:850->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testWeCanCancelTasks:282->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testTemplateMatch:341->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureTemplateBuilderLiveTest>BaseTemplateBuilderLiveTest.testTemplateBuilderWithLoginUserSpecified:189->BaseTemplateBuilderLiveTest.tryOverrideUsingPropertyKey:213 expected [[user=foo, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=true]] but found [[user=jclouds, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=false]]
  AzureComputeImageExtensionLiveTest>BaseImageExtensionLiveTest.testCreateImage:100 » RunNodes
  VirtualMachineApiLiveTest.testCapture:192 » Runtime error reading from stream,...

Tests run: 110, Failures: 9, Errors: 0, Skipped: 17
```

where

```
testCapture(org.jclouds.azurecompute.arm.features.VirtualMachineApiLiveTest)  Time elapsed: 0.279 sec  <<< FAILURE!
java.lang.RuntimeException: error reading from stream, parsing object named [resources] from http response {statusCode=202, message=Accepted, headers={Date=[Mon, 26 Sep 2016 16:27:04 GMT], Location=[https://management.azure.com/subscriptions/610bba05-d7a7-4567-96af-48ecbd09453b/providers/Microsoft.Compute/locations/westeurope/operations/2f1407a3-5130-4538-83b5-afa64606fb0a?monitor=true&api-version=2015-06-15], OkHttp-Received-Millis=[1474907225580], OkHttp-Selected-Protocol=[http/1.1], OkHttp-Sent-Millis=[1474907225479], Pragma=[no-cache], Server=[Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0], Strict-Transport-Security=[max-age=31536000; includeSubDomains], x-ms-correlation-request-id=[74db5cce-8a6d-483f-b2f4-eaff4d1d70f1], x-ms-ratelimit-remaining-subscription-reads=[14310], x-ms-request-id=[b86aa0d1-4305-433f-a714-2bd7ccda2b3c], x-ms-routing-request-id=[WESTEUROPE:20160926T162705Z:74db5cce-8a6d-483f-b2f4-eaff4d1d70f1], x-ms-served-by=[829aaa51-e3b6-4886-885b-e8d2c2a9415c_131191600707625458]}, payload=[content=true, contentMetadata=[cacheControl=no-cache, contentDisposition=null, contentEncoding=null, contentLanguage=null, contentLength=0, contentMD5=null, contentType=application/unknown, expires=Thu Jan 01 01:00:00 CET 1970], written=false, isSensitive=false]}
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1415)
	at com.google.gson.stream.JsonReader.consumeNonExecutePrefix(JsonReader.java:1582)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
	at org.jclouds.http.functions.ParseFirstJsonValueNamed.apply(ParseFirstJsonValueNamed.java:73)
	at org.jclouds.http.functions.ParseFirstJsonValueNamed.apply(ParseFirstJsonValueNamed.java:44)
	at org.jclouds.rest.internal.InvokeHttpMethod.invoke(InvokeHttpMethod.java:90)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:73)
	at org.jclouds.rest.internal.InvokeHttpMethod.apply(InvokeHttpMethod.java:44)
	at org.jclouds.reflect.FunctionalReflection$FunctionalInvocationHandler.handleInvocation(FunctionalReflection.java:117)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at com.sun.proxy.$Proxy90.captureStatus(Unknown Source)
	at org.jclouds.azurecompute.arm.compute.config.AzureComputeServiceContextModule$ImageDonePredicate.apply(AzureComputeServiceContextModule.java:265)
	at org.jclouds.azurecompute.arm.compute.config.AzureComputeServiceContextModule$ImageDonePredicate.apply(AzureComputeServiceContextModule.java:253)
	at org.jclouds.util.Predicates2$RetryablePredicate.apply(Predicates2.java:117)
	at org.jclouds.azurecompute.arm.features.VirtualMachineApiLiveTest.testCapture(VirtualMachineApiLiveTest.java:192)
```

hope to fix it soon

**Comment by nacx** [comment]
Yay! This is great progress @andreaturli!

**Comment by andreaturli** [comment]
@nacx I think we are good to merge this
```
Results :

Failed tests:
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCompareSizes:887->BaseComputeServiceLiveTest.doCompareSizes:891 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCreateAndRunAService:733->BaseComputeServiceLiveTest.createAndRunAServiceInGroup:747->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testImageById:212 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testOptionToNotBlock:850->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testWeCanCancelTasks:282->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testTemplateMatch:341->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureTemplateBuilderLiveTest>BaseTemplateBuilderLiveTest.testTemplateBuilderWithLoginUserSpecified:189->BaseTemplateBuilderLiveTest.tryOverrideUsingPropertyKey:213 expected [[user=foo, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=true]] but found [[user=jclouds, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=false]]
  AzureComputeImageExtensionLiveTest>BaseImageExtensionLiveTest.testCreateImage:100 » RunNodes

Tests run: 108, Failures: 8, Errors: 0, Skipped: 17
```

**Comment by andreaturli** [comment]
@nacx I think we are good to merge this
```
Results :

Failed tests:
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCompareSizes:887->BaseComputeServiceLiveTest.doCompareSizes:891 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testCreateAndRunAService:733->BaseComputeServiceLiveTest.createAndRunAServiceInGroup:747->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testImageById:212 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testOptionToNotBlock:850->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testWeCanCancelTasks:282->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureComputeServiceLiveTest>BaseComputeServiceLiveTest.testTemplateMatch:341->BaseComputeServiceLiveTest.buildTemplate:541 » Provision
  AzureTemplateBuilderLiveTest>BaseTemplateBuilderLiveTest.testTemplateBuilderWithLoginUserSpecified:189->BaseTemplateBuilderLiveTest.tryOverrideUsingPropertyKey:213 expected [[user=foo, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=true]] but found [[user=jclouds, passwordPresent=true, privateKeyPresent=false, shouldAuthenticateSudo=false]]
  AzureComputeImageExtensionLiveTest>BaseImageExtensionLiveTest.testCreateImage:100 » RunNodes

Tests run: 108, Failures: 8, Errors: 0, Skipped: 17
```

**Comment by nacx** [comment]
Absolutely! You rock!

**Comment by andreaturli** [comment]
merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/c458bafd)

**Pull request closed without merging**
