### PR TITLE
DockerTemplateOptions: use the correct return type

### PR DESCRIPTION
**Pull request by andreaturli**
@grkvlt and @neykov can you give a quick review?

### CODE REVIEW

**Comment by grkvlt** [comment]
Looks fine. Note that you could also at the same time remove the casting from the `Builder` static methods, as it isn't needed. So the static method for `env` becomes:

```Java
/**
 * @see DockerTemplateOptions#env(Iterable)
 */
public static DockerTemplateOptions env(Iterable<String> env) {
   DockerTemplateOptions options = new DockerTemplateOptions();
   return options.env(env);
}
```

And the same for all the other options that are defined in this class.

**Comment by neykov** [comment]
+1

**Comment by andreaturli** [comment]
Thanks @grkvlt for your tip ;)
Merging as soon as the builder is green

**Comment by andreaturli** [comment]
Merged at http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/eae89101
and backported to 1.9.x

**Pull request closed without merging**
