### PR TITLE
fix azure DataVirtualHardDiskHandler

### PR DESCRIPTION
**Pull request by andreaturli**
This backports to 1.9.x a fix that was already done into master

### CODE REVIEW

**Comment by nacx** [comment]
+1!

**Comment by andreaturli** [comment]
thanks @nacx !

**Comment by andreaturli** [comment]
Merged at [1.9.x](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/610f26de)

**Comment by heidsoft** [comment]
@andreaturli  jclouds-lab the docker project image.json is error ,Docker now image no parentid, but parent.
e.g:
```
{
    "Architecture": "amd64",
    "Author": "",
    "Comment": "",
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "docker-registry"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DOCKER_REGISTRY_CONFIG=/docker-registry/config/config_sample.yml",
            "SETTINGS_FLAVOR=dev"
        ],
        "ExposedPorts": {
            "5000/tcp": {}
        },
        "Hostname": "dd360632d03c",
        "Image": "c3736b5cf3ab13c8c34e04a6c19b771a3cc941fa25b32c4d80cde9a7a7ff7535",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": [],
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Container": "3af3b4d0c90c13a0c4f9f555013b45b2f7b055c2117d2736b5ebccd55f916d17",
    "ContainerConfig": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) CMD [\"docker-registry\"]"
        ],
        "CpuShares": 0,
        "Cpuset": "",
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "DOCKER_REGISTRY_CONFIG=/docker-registry/config/config_sample.yml",
            "SETTINGS_FLAVOR=dev"
        ],
        "ExposedPorts": {
            "5000/tcp": {}
        },
        "Hostname": "dd360632d03c",
        "Image": "c3736b5cf3ab13c8c34e04a6c19b771a3cc941fa25b32c4d80cde9a7a7ff7535",
        "Labels": {},
        "MacAddress": "",
        "Memory": 0,
        "MemorySwap": 0,
        "NetworkDisabled": false,
        "OnBuild": [],
        "OpenStdin": false,
        "PortSpecs": null,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": null,
        "WorkingDir": ""
    },
    "Created": "2015-07-18T08:37:20.952192088Z",
    "DockerVersion": "1.6.2",
    "Id": "80aa76e58d06b7bf91fbea2fb8a8a87235ca360b9f749ca288db2eedd2ef0ab3",
    "Os": "linux",
    "Parent": "c3736b5cf3ab13c8c34e04a6c19b771a3cc941fa25b32c4d80cde9a7a7ff7535",
    "Size": 0,
    "VirtualSize": 427916472
}
```

so  I can't get the correct value when calling list image

**Comment by nacx** [comment]
@heidsoft this PR is about Azure. Please, move your comment to the appropriate pull request or to the jclouds dev@ mailing list.

**Pull request closed without merging**
