### PR TITLE
support docker api v1.18

### PR DESCRIPTION
**Pull request by andreaturli**
@jbartece could you please review this and test if that fixes https://issues.apache.org/jira/browse/JCLOUDS-900 ?

### CODE REVIEW

**Comment by jbartece** [comment]
I'll try to do it on Monday

**Comment by jbartece** [comment]
@andreaturli Hi. I tested it and it doesn't fix the JCLOUDS-900. I think that this bug is not related to the version of Docker API. It looks like it is internal JClouds bug. I found one similar issue: https://issues.apache.org/jira/browse/JCLOUDS-857

**Comment by andreaturli** [comment]
@jbartece could you simply run just `ContainerApiLiveTest` and paste the stacktrace of the error on gist, please?

**Comment by jbartece** [comment]
I ran it and got error, but it is probably caused by the wrong environment. Could you check the logs and tell me what should I change, please?  https://gist.github.com/jbartece/4cad0bd49f585a6c004d

**Comment by andreaturli** [comment]
can you try with

```
mvn clean install -PLive -Dtest.docker.identity=/path/to/cert.pem -Dtest.docker.credential=/path/to//key.pem -Dtest.docker.endpoint=https://0.0.0.0:4243
```

**Comment by jbartece** [comment]
I really don't have much experience with the security stuff. Do you have any test certificates generated or some HOW-TO manual?

**Comment by jbartece** [comment]
Is it possible to test it without authentication?

**Comment by jbartece** [comment]
I found in IRC logs, that it is possible to run the test without authentication using: mvn clean install -Plive -Dtest.docker.identity=root -Dtest.docker.credential=pwd -Dtest.docker.endpoint=http://192.168.59.103:2375

**Comment by andreaturli** [comment]
yes it is possible, you filed a bug for that already. Be sure to start your docker engine on `http`

**Comment by jbartece** [comment]
I rerun the tests and got: https://gist.github.com/jbartece/c7e4f4b993a344726321

**Comment by nacx** [comment]
@andreaturli @jbarteceis there something left to be able to merge this PR?

**Comment by jbartece** [comment]
@nacx As for me you can merge it

**Comment by nacx** [comment]
@andreaturli good to rebase & merge?

**Comment by andreaturli** [comment]
I think #221 supercedes this PR. @jbartece can you please look at it and report here, if #174 can be closed? Thanks!

**Comment by andreaturli** [comment]
close as #221 fix the same issues and has been already merged.

**Pull request closed without merging**
