### PR TITLE
JCLOUDS-702: JClouds ProfitBricks provider - Snapshots API

### PR DESCRIPTION
**Pull request by baldwinSPC**
Hi All:

Here's a pull request to surface the snapshot capabilities within jClouds Labs for the ProfitBricks provider. We are working in conjunction with @devcsrj .  Please let us know if there are any questions or issues. 

Thanks. 
-matt

### CODE REVIEW

**Comment by baldwinSPC** [comment]
@nacx Hi, we've been working on this with RJ. We have the PR passing tests so we're just waiting on a review to merge. Let me know if there are any issues or changes that need to happen. Thanks.

**Comment by jasminSPC** [comment]
@nacx I've just rebased to the latest master version.
Did I miss anything?

**Comment by nacx** [comment]
I think the starting point of this PR is not the right one, as I see some merge commits there too. If you have a look at the modified files in the PR, you will see *many* files that are not related to the changes for the SnapshotApi. There is the entire pom.xml that appears as changed, the ServerApi and so on.

Please, clean the pull request in a way that it **only** cointains the relevant changes and the relevant commits (the PR has 50 commits right now most of them unrelated to the changes). Otherwise it will be difficult to review, but more important, we won't know how to merge it.

**Comment by baldwinSPC** [comment]
@nacx We're forked from a fork. We're going to re-do our repo, the branch, and then re-send a new PR with meeting hopefully your requirements. We're not sure how to clean it up otherwise. This is work we're doing in tandem with another user.

**Pull request closed without merging**
