### PR TITLE
JCLOUDS-1009 JCLOUDS-1029: Fix tests and try to avoid deadlocks

### PR DESCRIPTION
**Pull request by rcoedo**

### CODE REVIEW

**Comment by nacx** [comment]
Thanks @rcoedo ! Build is happy, but let's trigger a couple more :) rebuild please

**Comment by rcoedo** [comment]
rebuild please

**Comment by rcoedo** [comment]
Is this the problem we were having before? Is there a way I can see the log?

**Comment by nacx** [comment]
If I build only the JDBC api (`mvn clean install -pl jdbc`), the build succeeds. However, when building the entire labs repo (in OSX) I get this failure consistently:

```bash
-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 162, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 56.79 sec <<< FAILURE! - in TestSuite
testAllLocations(org.jclouds.jdbc.integration.HibernateHsqldbServiceIntegrationTest)  Time elapsed: 0.029 sec  <<< FAILURE!
java.lang.NullPointerException: null
	at org.jclouds.blobstore.integration.internal.BaseServiceIntegrationTest$1$1.apply(BaseServiceIntegrationTest.java:59)
	at org.jclouds.blobstore.integration.internal.BaseServiceIntegrationTest$1$1.apply(BaseServiceIntegrationTest.java:57)
	at com.google.common.collect.Iterators.indexOf(Iterators.java:773)
	at com.google.common.collect.Iterators.any(Iterators.java:679)
	at com.google.common.collect.Iterables.any(Iterables.java:619)
	at org.jclouds.blobstore.integration.internal.BaseServiceIntegrationTest$1.run(BaseServiceIntegrationTest.java:57)
	at org.jclouds.blobstore.integration.internal.BaseBlobStoreIntegrationTest.assertConsistencyAware(BaseBlobStoreIntegrationTest.java:233)
	at org.jclouds.blobstore.integration.internal.BaseBlobStoreIntegrationTest.assertConsistencyAware(BaseBlobStoreIntegrationTest.java:253)
	at org.jclouds.blobstore.integration.internal.BaseServiceIntegrationTest.testAllLocations(BaseServiceIntegrationTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```
Any ideas?

**Comment by nacx** [comment]
@rcoedo the build failed for an external reason. A rebuild should fix it. The failure I pasted is a new one.
You can see the logs of the build by clicking the "Details" link in the box above. That will take you to our Jenkins server, and there you can click "Console output" to see the logs of the build.

**Comment by nacx** [comment]
rebuild please

**Comment by nacx** [comment]
Noe you can also follow the "Details" link and go to the console output while the build is running to see the live output of the build.

**Comment by rcoedo** [comment]
I'm building the entire labs repository in OSX too and I'm not able to reproduce that error.

**Comment by nacx** [comment]
Still getting the same error... :( This is my env:
```bash
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
Maven home: /opt/maven
Java version: 1.7.0_51, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11", arch: "x86_64", family: "mac"
```

**Comment by nacx** [comment]
Running the tests with `-DthreadCount=1` worked, but looking at the pom that is already configure. Will try to figure out why that is not being taken into account unless manually specified...

**Comment by nacx** [comment]
Configuring the threadCount globally in the jdbc pom fixes the issues I'm experiencing. I'm still not sure why it makes the difference, as the integration tests should already have it configured, and the unit tests should not interfere, but the fact is that this is fixing the mentioned issues. Here is the diff. Worth adding it to the PR?

```diff
diff --git a/jdbc/pom.xml b/jdbc/pom.xml
index 4408891..da9e43c 100644
--- a/jdbc/pom.xml
+++ b/jdbc/pom.xml
@@ -125,6 +125,9 @@
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-surefire-plugin</artifactId>
+        <configuration>
+          <threadCount>1</threadCount>
+        </configuration>
         <executions>
           <execution>
             <id>integration</id>
```

**Comment by rcoedo** [comment]
That's wierd, it doesn't happen on my OSX (10.10). I just pushed the pom configuration.

**Comment by nacx** [comment]
Squashed and pushed to master as [c759e217](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/c759e217). Thanks for the quick fix @rcoedo!

**Pull request closed without merging**
