### PR TITLE
ProfitBricks Compute API

### PR DESCRIPTION
**Pull request by mirza-spc**
@jasminSPC

### CODE REVIEW

**Comment by nacx** [comment]
This PR is a mess. Just looking at the first two files, it contains unresolved merge conflicts. Please, amend and submit a proper patch that can be reviewed.

Also take your time to describe the contents of the pull request. The summary for this PR shows that there are 3.682 lines added, and this is huge to review, and especially if there is no context nor explanation of the contents of the PR. Please, describe what it adds: just the implementation of an interface? additional things? which live tests have been added and which is their status?

**Comment by mirza-spc** [comment]
This isn't ment to be a complete PR. We've only opened it because we needed your with a few issues.

**Comment by nacx** [comment]
> This isn't ment to be a complete PR. We've only opened it because we needed your with a few issues.

In any case, this does not even compile. There are java files with diff markers in there, which denotes that not enough care have been put on a simple "git pull / git merge".

This said, if you need some feedback, the best way to get it is to write an appropriate description, and ask there for the feedback you need. We don't have a crystall ball to guess the purpose of the pull request, its completeness, or what feedback you do exactly need.

Please, open a proper pull request, and take your time to write a description that properly gives us context and the questions you have, so we can start a proper discussion.

**Comment by nacx** [comment]
Any updates here?

**Comment by mirza-spc** [comment]
So I'm not sure how to reconcile the differences with the Compute Interface and PB REST API. Thus, I cannot get Compute live test to pass.

Take for example Compute Interface:
```
   Iterable<L> listLocations();

   N getNode(String id);

   // TODO consider making reboot/resume/suspend return the node they affected
   void destroyNode(String id);

   void rebootNode(String id);

   void resumeNode(String id);

   void suspendNode(String id);
```

However, in PB REST, additional data center id is required.

**Comment by nacx** [comment]
There are other providers that face this issue, and they encode the region in the node ID. You can have a look at how the [OpenStack Nova](https://github.com/jclouds/jclouds/blob/master/apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/compute/NovaComputeServiceAdapter.java#L221-L233) provider returns the nodes. It uses a `ServerInRegion` internal entity, just to transport all the region information to the [node transformation function](https://github.com/jclouds/jclouds/blob/master/apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/compute/functions/ServerInRegionToNodeMetadata.java#L102-L103). So nodes IDs in nova are something like "regionA/i-0001". Then the adapter takes this convention into account elsewhere, such as when [getting a node by id](https://github.com/jclouds/jclouds/blob/master/apis/openstack-nova/src/main/java/org/jclouds/openstack/nova/v2_0/compute/NovaComputeServiceAdapter.java#L253-L258). The use of that `ServerInRegion` class is a clean way to encapsulate all this ID encoding behavior across the entire the portable abstraction layer.

**Comment by jasminSPC** [comment]
rebuild please

**Comment by alibazlamit** [comment]
@nacx Do you have any idea what could be causing this issue:

  NoSuchElementException on node b99a9c31-a652-4212-823c-5a5de03b6ece/3054f358-b187-4684-8094-44d0832350d7:
java.util.NoSuchElementException: could not connect to any ip address port 22 on node {id=b99a9c31-a652-4212-823c-5a5de03b6ece/3054f358-b187-4684-8094-44d0832350d7, providerId=b99a9c31-a652-4212-823c-5a5de03b6ece/3054f358-b187-4684-8094-44d0832350d7, name=profitbricks-rests-9f6, location={scope=ZONE, id=b99a9c31-a652-4212-823c-5a5de03b6ece, description=computeServiceLiveTest, parent=us/las, metadata={version=4, state=AVAILABLE}}, group=profitbricks-rests, os={family=linux, description=linux, is64Bit=false}, status=RUNNING[AVAILABLE], loginPort=22, publicAddresses=[158.222.103.134], hardware={id=cpu=1,ram=1024,disk=10, providerId=cpu=1,ram=1024,disk=10, name=cpu=1,ram=1024,disk=10, location={scope=ZONE, id=b99a9c31-a652-4212-823c-5a5de03b6ece, description=computeServiceLiveTest, parent=us/las, metadata={version=4, state=AVAILABLE}}, processors=[{cores=1.0, speed=1.0}], ram=1024, volumes=[{id=f3fad40c-e47a-4ef3-bac8-27e997484c62, type=LOCAL, size=10.0, device=1, bootDevice=false, durable=true}], hypervisor=kvm, supportsImage=ALWAYS_TRUE}, loginUser=root}
 at org.jclouds.compute.util.ConcurrentOpenSocketFinder.findOpenSocketOnNode(ConcurrentOpenSocketFinder.java:107)
 at org.jclouds.compute.strategy.CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.call(CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.java:128)
 at org.jclouds.compute.strategy.CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.apply(CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.java:144)
 at org.jclouds.compute.strategy.CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.apply(CustomizeNodeAndAddToGoodMapOrPutExceptionIntoBadMap.java:50)
 at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713)
 at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 at java.lang.Thread.run(Thread.java:745)

**Comment by nacx** [comment]
This is usually because the port 22 is filtered in the VM (do you need to configure a firewall to enable access to that port?) or because the VM does not have a reachable ip address, or because the adapter/transformation function are not returning properly a reachable ip address when returning the node. It could be any of them.

I would be more than happy to help, but in order to do that, I need to be able to focus on the code that really matters. If you fix the pull request and remove all the invalid code (merge conflicts, etc) and push a proper, clean, rebased branch, I'll have a look at it and try to help!

**Comment by alibazlamit** [comment]
@nacx I can push of course but the Compute is still a work in progress, that's OK?

**Comment by nacx** [comment]
Yes, that is OK, we can work together in the PR to fix things. This is a good place to discuss the code and propose changes, and track progress with the commits. Feel free to close this one and open a new one if that is easier for you.

**Comment by alibazlamit** [comment]
@jasminSPC  Could you close this PR i don't have the permission to

**Comment by alibazlamit** [comment]
@nacx i am working on fixing the PR mean while could you tell me if you came across this
`INFO: << configured node(1821134a-fa51-4d3a-8a3d-da1e891dc4d2/fc621963-76bc-495f-8585-afd0885d33a9) with bash: java: command not found and jetty head: cannot open '/usr/local/jetty/VERSION.txt' for reading: No such file or directory in 27s
`
i managed to pass the issue with the port 22 now i got this.

**Comment by jasminSPC** [comment]
@nacx could you close this PR. We will have to open a new one for Profitbricks compute

**Pull request closed without merging**
