### PR TITLE
JCLOUDS-853: Improve Create VirtualMachine Deployment

### PR DESCRIPTION
**Pull request by hsbhathiya**
Rebased #154  on master

### CODE REVIEW

**Comment by nacx** [comment]
Can you please format the code to use a 3 space indent? The diff shows many changed lines only due to this making it quite difficult to see the actual changes.

**Comment by ilgrosso** [comment]
Hi @hsbhathiya, can you please make the format changes requested by @nacx?

**Comment by nacx** [comment]
@hsbhathiya we really look forward to having this merged. Is there any chance you have some time to dedicate to this PR?

**Comment by hsbhathiya** [comment]
Sorry. I was bit busy last few days. I'll make those changes tomorrow.

**Comment by hsbhathiya** [comment]
@nacx 
Moved to https://github.com/jclouds/jclouds-labs/pull/175 with changes

**Pull request closed without merging**
