### PR TITLE
Support supplying key and certificate to Docker as data

### PR DESCRIPTION
**Pull request by grkvlt**
See #271 for equivalent changes in 1.9.x branch

### CODE REVIEW

**Comment by andreaturli** [comment]
hi @grkvlt could you just comment on why is this needed?

**Comment by grkvlt** [comment]
@andreaturli This was to allow passing in the certificate data directly if it was not available as a file, and makes it easier in some cases to use the jclouds driver with Brooklyn

**Comment by andreaturli** [comment]
cool, thanks.
lgtm. Merging now

**Comment by andreaturli** [comment]
merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/c5d845d3)

**Pull request closed without merging**
