### PR TITLE
BlobStore API for Orion based back-ends

### PR DESCRIPTION
**Pull request by timur87**

### CODE REVIEW

**Comment by everett-toews** [comment]
Thanks for the pull request but it's release week in jclouds and that means it's time to clean up the PR queue. This PR will be over 6 months old as of April 1. If you intend to continue work on it, please make a comment by April 2. Otherwise it will be closed on April 3.

**Comment by timur87** [comment]
What do you mean by continue working on it? I assume you are not planning to merge it when we consider that the request is open since Nov 30, 2013. So does it make sense to continue working on it?

**Comment by everett-toews** [comment]
I don't know the history of this PR but the fact that it's been open since Nov. 30, 2013 is odd. 

@aledsage @demobox @andrewgaul Does it make sense to continue working on this?

**Comment by andrewgaul** [comment]
@timur87 Sorry we have ignored this as we have been improving some of the existing providers as well as paying down some internal technical debt.  I signed up for an OrionHub account but unfortunately this pull request has bit-rotted due to API changes, especially `AsyncBlobStore` but also some new portable APIs.  Could you rebase and resubmit so I can test this?

Generally we have little familiarity with Eclipse Orion.  Can you give some insights into its intended use, especially contrasting with the existing S3- and Swift-based protocols?  We might intake this into labs if you are willing to maintain it but hosting it externally could have advantages for you.

**Comment by andrewgaul** [comment]
@timur87 Seems like we dropped the ball on this.  If you rebase this we can reopen and review this commit.

**Pull request closed without merging**
