### PR TITLE
Update endpoint to v3

### PR DESCRIPTION
**Pull request by alibazlamit**
@nacx Could you please merge this PR, i have updated the endpoint in the ProfitBricksProviderMetadata to the latest API endpoint v3 alongside with some features of the v3 version.

Thanks

### CODE REVIEW

**Comment by nacx** [comment]
LGTM. Can you share the results of the live tests?

**Comment by alibazlamit** [comment]
@nacx Live tests results [here](https://gist.github.com/alibazlamit/1e6a4d199737c34aa7a3522d7ba774a2).

Thanks!

**Comment by nacx** [comment]
Pushed to [master](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/7aa033a9) and [2.0.x](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/1a622a3b).
I just pushed your first commit (I asked for the test result since I found the same issue when running the tests locally, and opened https://github.com/jclouds/jclouds-labs/pull/391). I'll merge that PR to include the new location since it has the right ISO code and also adds it to the tests.

**Comment by nacx** [comment]
Looks good. That's the right dependency to be added...
http://search.maven.org/#artifactdetails%7Corg.apache.jclouds.labs%7Cprofitbricks-rest%7C2.0.1%7Cbundle

**Pull request closed without merging**
