### PR TITLE
JCLOUDS-826: BaseServiceIntegrationTest for jdbc

### PR DESCRIPTION
**Pull request by rcoedo**

### CODE REVIEW

**Comment by zack-shoylev** [comment]
+1

**Comment by zack-shoylev** [comment]
I got an exception while testing:

```
testAllLocations(org.jclouds.jdbc.integration.HibernateHsqldbServiceIntegrationTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.NullPointerException: null
        at org.jclouds.blobstore.integration.internal.BaseServiceIntegrationTest$1$1.apply(BaseServiceIntegrationTest.java:59)
        at org.jclouds.blobstore.integration.internal.BaseServiceIntegrationTest$1$1.apply(BaseServiceIntegrationTest.java:57)
        at com.google.common.collect.Iterators.indexOf(Iterators.java:773)
        at com.google.common.collect.Iterators.any(Iterators.java:679)
        at com.google.common.collect.Iterables.any(Iterables.java:619)
        at org.jclouds.blobstore.integration.internal.BaseServiceIntegrationTest$1.run(BaseServiceIntegrationTest.java:57)
        at org.jclouds.blobstore.integration.internal.BaseBlobStoreIntegrationTest.assertConsistencyAware(BaseBlobStoreIntegrationTest.java:233)
        at org.jclouds.blobstore.integration.internal.BaseBlobStoreIntegrationTest.assertConsistencyAware(BaseBlobStoreIntegrationTest.java:253)
        at org.jclouds.blobstore.integration.internal.BaseServiceIntegrationTest.testAllLocations(BaseServiceIntegrationTest.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at org.testng.TestRunner.privateRun(TestRunner.java:767)
        at org.testng.TestRunner.run(TestRunner.java:617)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
        at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
```

but was not able to reproduce.

**Comment by zack-shoylev** [comment]
merged

**Comment by rcoedo** [comment]
Maybe it had something to do with a previous database file on your target folder. I'll check it just in case.

**Pull request closed without merging**
