### PR TITLE
re-use java-xmlbuilder.version property in mvn

### PR DESCRIPTION
**Pull request by andreaturli**
Merge only when https://github.com/jclouds/jclouds/pull/785 will be closed

### CODE REVIEW

**Comment by nacx** [comment]
lgtm.

**Comment by andreaturli** [comment]
thanks @nacx 

Merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/100bc250) and backported at [1.9.x](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/c55f6363)

**Comment by andreaturli** [comment]
Merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/100bc250) and backported to [1.9.x](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/c55f6363)

**Comment by andreaturli** [comment]
thanks @nacx

**Pull request closed without merging**
