### PR TITLE
azurecompute: improvements to the domain objects

### PR DESCRIPTION
**Pull request by andreaturli**
@hsbhathiya could you please have a look?

### CODE REVIEW

**Comment by nacx** [comment]
Just one comment: In the domain objects, google auto already guarantees immutability, but when there are lists, we have to make sure they are immutable too. Change all `create` methods that receive lists, and use `ImmutableList.copyOf` instead of assigning the lists directly to make sure they are immutable too.
+1 to merge once this is done. Thanks @andreaturli and @hsbhathiya!

**Comment by andreaturli** [comment]
@nacx mind merging it?

**Comment by nacx** [comment]
Changes lgtm. let's squash the commits and merge it yourself :) Thanks!

**Comment by andreaturli** [comment]
Merged at https://git1-us-west.apache.org/repos/asf?p=jclouds-labs.git;a=blob;f=azurecompute/src/test/java/org/jclouds/azurecompute/xml/NetworkSecurityGroupHandlerTest.java;hb=a34e62ca

**Pull request closed without merging**
